pip install flask
pip install flask-wtf
pip install flask-sqlalchemy
pip install flask-migrate
pip install flask-login
pip install pyjwt
pip install flask-mail
pip install flask-bootstrap
pip install flask-moment
pip install guess-language_spirit
pip install flask-babel
pip install apscheduler