"""added user type

Revision ID: 2a7373e245af
Revises: a8de586276a9
Create Date: 2018-06-12 17:06:32.427938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a7373e245af'
down_revision = 'a8de586276a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_type', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_user_user_type'), 'user', ['user_type'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_user_type'), table_name='user')
    op.drop_column('user', 'user_type')
    # ### end Alembic commands ###
