"""added humidity for threshold

Revision ID: 3ebe410c3647
Revises: 4a475c666da5
Create Date: 2018-06-12 18:17:36.799952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ebe410c3647'
down_revision = '4a475c666da5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_threshold', sa.Column('humid', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor_threshold', 'humid')
    # ### end Alembic commands ###
