"""CSV table

Revision ID: a8de586276a9
Revises: f2f0a44624d3
Create Date: 2018-06-12 02:34:20.244766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8de586276a9'
down_revision = 'f2f0a44624d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CSV',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=140), nullable=True),
    sa.Column('sensor_type', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CSV_timestamp'), 'CSV', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_CSV_timestamp'), table_name='CSV')
    op.drop_table('CSV')
    # ### end Alembic commands ###
