"""added sensor

Revision ID: f2f0a44624d3
Revises: e66704a4632a
Create Date: 2018-06-10 15:44:51.760880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2f0a44624d3'
down_revision = 'e66704a4632a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_threshold',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temp', sa.String(length=140), nullable=True),
    sa.Column('smoke', sa.String(length=140), nullable=True),
    sa.Column('water', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_threshold')
    # ### end Alembic commands ###
